name: Cloud Run Build and Deploy
on: [push]

env:
  WORKLOAD_IDENTITY_PROVIDER: projects/644621961258/locations/global/workloadIdentityPools/myidentity-pool/providers/myidentity-provider
  SERVICE_ACCOUNT: sa-wif@helloworld-454409.iam.gserviceaccount.com
  PROJECT: helloworld-454409
  REGION: europe-west9
  REGISTRY: europe-west9-docker.pkg.dev

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider:  ${{env.WORKLOAD_IDENTITY_PROVIDER}}
          service_account:  ${{env.SERVICE_ACCOUNT}}

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.auth_token }}
          registry: ${{env.REGISTRY}}

      - name: Construction du Livrable
        run: |-
          DOCKER_TAG="${{env.REGISTRY}}/${{env.PROJECT}}/pocsupermarche/articles:${{ github.sha }}"
          docker build -f Dockerfile-gcp --build-arg ACCESS_TOKEN=${{ steps.auth.outputs.access_token }}  --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider:  ${{env.WORKLOAD_IDENTITY_PROVIDER}}
          service_account:  ${{env.SERVICE_ACCOUNT}}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: spmkt-articles-${{env.ENV}}
          region: ${{env.REGION}}
          image: ${{env.REGISTRY}}/${{env.PROJECT}}/pocsupermarche/articles:${{ github.sha }}
